apiVersion: 1
datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: "http://tempo:3200"
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
      tracesToMetrics:
        datasourceUid: mimir
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: mimir

  - name: Mimir
    uid: mimir
    type: prometheus
    access: proxy
    url: "http://mimir:9009/prometheus"
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
