# dnsmasq config for DNS poisoning scenarios
# By default, resolve all queries via Docker's embedded DNS
server=/./127.0.0.11#53
no-resolv
bind-interfaces
listen-address=0.0.0.0
domain-needed
bogus-priv
log-queries
log-facility=-
